### PR TITLE
General: Add mac support

### PR DESCRIPTION
**Pull request by DarthMDev**
This change is [Reviewable](https://reviewable.io/reviews/toontown-open-source-initiative/toontown-school-house/37)

### CODE REVIEW

**Comment by 2Epik4u** [comment]
You dont need wine to get ttsh working, You can just build this panda3d https://github.com/rocketprogrammer/ttoffline-panda3d

**Comment by DarthMDev** [comment]
Python 2 doesn’t work on mac , it just crashes

**Comment by DarthMDev** [comment]
The solution is convert the game to python 3 but that causes some issue I haven’t seen other tt projects have

**Comment by ComradeNapCali** [comment]
This seems like a really impractical and hacky solution. You are "bandaidding" the issue rather then fixing the actual issue.
Wine just wraps Windows executables to work on Unix-like systems without any mods. But that is still not "native" support, and just bypasses the real problem.

It would be way better to compile [ttoff-panda3d](https://github.com/rocketprogrammer/ttoffline-panda3d) for macOS on Python 3 and then use that on School House, as that is the Panda3D that School House uses.

If I was a maintainer on this project, I would have rejected this, sorry.

Also:
> Python 2 doesn’t work on mac , it just crashes

I don't know why Python 2 is crashing on you; you probably are screwing something up on your end.

> The solution is convert the game to python 3

There are some servers that have School House for Python 3, but they are public right now, due to buggy behavior, and lack of public-friendly instructions. You are going to have to wait.

**Pull request closed without merging**
