### PR TITLE
MagicWordIndex: Fix district crash with setgm magic word

### PR DESCRIPTION
**Pull request by DarthMDev**

### CODE REVIEW

**Comment by DarthMDev** [comment]
Can one of the students or contributors review this please.

**Comment by danr789** [comment]
Both of the 4 GM seem to work Fine with 0 Crashes

**Comment by DarthMDev** [comment]
That's odd a long time ago  I got a district reset related to this and that's what this fix is for

**Review by darkhappy — APPROVED** [review]
lgtm!

**Pull request merged**
